import type { NextPage } from 'next'
import Head from 'next/head'

import { Layout } from '@/components/Layout'
import { Hero } from '@/components/Homepage'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Home - Mohamed Elidrissi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
    </Layout>
  )
}

export default Home
